language: node_js
node_js:
- 11.14.0
warnings_are_errors: false
env:
  global:
    - SERVER_IP_ADDRESS=ec2-18-224-56-34.us-east-2.compute.amazonaws.com
branches:
  only:
  - development
  - master
after_failure:
- npm run coverage
before_deploy:
- npm run build
- openssl aes-256-cbc -K $encrypted_2480938aff30_key -iv $encrypted_2480938aff30_iv
  -in ltuserssh_rsa.enc -out ltuserssh_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./ltuserssh_rsa
- ssh-add ./ltuserssh_rsa
- mkdir -p ~/.ssh  &&  echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking
  no" >> ~/.ssh/config
- ssh-keyscan -H 18.224.56.34 >> ~/.ssh/known_hosts
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - stage: build
    script: npm run build
  - stage: deploy
    deploy:
      provider: script
      skip_cleanup: true
      local_dir: build
      script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/* ltuser@ec2-18-224-56-34.us-east-2.compute.amazonaws.com:/home/ltuser/lt-frontend
      on:
        branch: master
stages:
- name: build
  if: branch = development
- name: deploy
  if: branch = master

